#!/usr/bin/env node
// Convert a filled-in draft CSV into src/data/defaultDraftClasses.ts so the
// dataset ships as the standard classes for every player.
//
// Usage:  node scripts/csvToDefaults.mjs path/to/filled.csv
//
// Mirrors the parser in src/data/draftImport.ts (birthYear primary, age
// fallback, pipe-separated traits, # comment lines ignored).

import { readFileSync, writeFileSync } from 'node:fs';

const IDEOLOGIES = ['LW Populist', 'Progressive', 'Liberal', 'Moderate', 'Conservative', 'Traditionalist', 'RW Populist'];
const TRAITS = ['Charismatic','Integrity','Efficient','Orator','Debater','Propagandist','Crisis Manager','Kingmaker','Numberfudger','Harmonious','Manipulative','Celebrity','Magician','Naval','Education','Economics','Business','Agriculture','Environment','Media','Nationalist','Globalist','Reformist','Military','Egghead','Leadership','Incompetent','Passive','Unlikable','Puritan','Domestic Apathy','Flip-Flopper','Corrupt','Scandalous','Frail','Controversial','Obscure','Traitor'];

function splitCsvLine(line) {
  const out = []; let cur = ''; let q = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (q) { if (c === '"' && line[i+1] === '"') { cur += '"'; i++; } else if (c === '"') q = false; else cur += c; }
    else if (c === '"') q = true;
    else if (c === ',') { out.push(cur); cur = ''; }
    else cur += c;
  }
  out.push(cur); return out;
}
const clamp = (s) => { const n = parseInt(String(s).trim(), 10); return Number.isNaN(n) ? 0 : Math.max(0, Math.min(5, n)); };
const ideo = (s) => IDEOLOGIES.find((i) => i.toLowerCase() === String(s).trim().toLowerCase()) ?? 'Moderate';
const trait = (s) => TRAITS.find((t) => t.toLowerCase() === String(s).trim().toLowerCase()) ?? null;

const file = process.argv[2];
if (!file) { console.error('Usage: node scripts/csvToDefaults.mjs path/to/filled.csv'); process.exit(1); }

const lines = readFileSync(file, 'utf8').split(/\r?\n/).filter((l) => l.trim() && !l.trim().startsWith('#'));
const header = splitCsvLine(lines[0]).map((h) => h.trim().toLowerCase());
const idx = (n) => header.indexOf(n);

const draftees = [];
for (let li = 1; li < lines.length; li++) {
  const cells = splitCsvLine(lines[li]);
  const g = (n) => { const i = idx(n); return i >= 0 && i < cells.length ? cells[i].trim() : ''; };
  const draftYear = parseInt(g('draftyear'), 10);
  const firstName = g('firstname'); const lastName = g('lastname');
  if (Number.isNaN(draftYear) || !firstName || !lastName) continue;
  const by = parseInt(g('birthyear'), 10);
  const ag = parseInt(g('age'), 10);
  let birthYear, age;
  if (!Number.isNaN(by)) { birthYear = by; age = Math.max(25, draftYear - by); }
  else if (!Number.isNaN(ag)) { age = ag; birthYear = draftYear - ag; }
  else { age = 35; birthYear = draftYear - 35; }
  const traits = g('traits') ? g('traits').split(/[|;]/).map(trait).filter(Boolean) : [];
  draftees.push({
    draftYear, firstName, lastName,
    state: (g('state') || 'ny').toLowerCase(),
    ideology: ideo(g('ideology')),
    birthYear, age,
    skills: { admin: clamp(g('admin')), legislative: clamp(g('legislative')), judicial: clamp(g('judicial')), military: clamp(g('military')), governing: clamp(g('governing')), backroom: clamp(g('backroom')) },
    command: clamp(g('command')),
    traits,
  });
}

const banner = `import type { ImportedDraftee } from '../types';

// =============================================================================
// STANDARD DRAFT CLASSES — shipped with the game for ALL players.
// AUTO-GENERATED by scripts/csvToDefaults.mjs. Do not hand-edit; regenerate
// from the source CSV instead.
// =============================================================================

export const DEFAULT_DRAFT_CLASSES: ImportedDraftee[] = ${JSON.stringify(draftees, null, 2)};
`;

writeFileSync(new URL('../src/data/defaultDraftClasses.ts', import.meta.url), banner);
console.log(`Wrote ${draftees.length} draftees to src/data/defaultDraftClasses.ts`);
