import type { ImportedDraftee } from '../types';

// =============================================================================
// CURATED BUILT-IN FALLBACK — small set (founders + marquee in-game figures).
// AUTO-GENERATED by scripts/legislatorsToDataset.mjs from the curated rows in
// scripts/seedDataset.mjs. The FULL ~12k historical set is loaded at runtime
// from public/standard-draft-classes.json; this is the offline fallback that
// keeps the 1772 inaugural draft working before/without that fetch.
// =============================================================================

export const DEFAULT_DRAFT_CLASSES: ImportedDraftee[] = [
  {
    "draftYear": 1772,
    "firstName": "Samuel",
    "lastName": "Adams",
    "state": "ma",
    "ideology": "LW Populist",
    "birthYear": 1722,
    "age": 50,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 4
    },
    "command": 1,
    "traits": [
      "Orator"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Thomas",
    "lastName": "Jefferson",
    "state": "va",
    "ideology": "RW Populist",
    "birthYear": 1743,
    "age": 29,
    "skills": {
      "admin": 3,
      "legislative": 4,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 1,
    "traits": [
      "Egghead"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Patrick",
    "lastName": "Henry",
    "state": "va",
    "ideology": "Traditionalist",
    "birthYear": 1736,
    "age": 36,
    "skills": {
      "admin": 1,
      "legislative": 4,
      "judicial": 2,
      "military": 1,
      "governing": 3,
      "backroom": 3
    },
    "command": 1,
    "traits": [
      "Orator",
      "Debater"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "John",
    "lastName": "Hancock",
    "state": "ma",
    "ideology": "Moderate",
    "birthYear": 1737,
    "age": 35,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 3,
      "backroom": 3
    },
    "command": 1,
    "traits": [
      "Celebrity"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "George",
    "lastName": "Clinton",
    "state": "ny",
    "ideology": "Moderate",
    "birthYear": 1739,
    "age": 33,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 1,
      "governing": 3,
      "backroom": 3
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Richard Henry",
    "lastName": "Lee",
    "state": "va",
    "ideology": "Conservative",
    "birthYear": 1732,
    "age": 40,
    "skills": {
      "admin": 2,
      "legislative": 4,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 0,
    "traits": [
      "Debater"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "John",
    "lastName": "Dickinson",
    "state": "de",
    "ideology": "Conservative",
    "birthYear": 1732,
    "age": 40,
    "skills": {
      "admin": 3,
      "legislative": 4,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Egghead"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Thomas",
    "lastName": "Paine",
    "state": "pa",
    "ideology": "Progressive",
    "birthYear": 1737,
    "age": 35,
    "skills": {
      "admin": 1,
      "legislative": 2,
      "judicial": 0,
      "military": 0,
      "governing": 0,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Propagandist",
      "Obscure"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Elias",
    "lastName": "Boudinot",
    "state": "nj",
    "ideology": "Progressive",
    "birthYear": 1740,
    "age": 32,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "George",
    "lastName": "Mason",
    "state": "va",
    "ideology": "Traditionalist",
    "birthYear": 1725,
    "age": 47,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Francis",
    "lastName": "Marion",
    "state": "sc",
    "ideology": "Traditionalist",
    "birthYear": 1732,
    "age": 40,
    "skills": {
      "admin": 0,
      "legislative": 0,
      "judicial": 0,
      "military": 4,
      "governing": 0,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Ethan",
    "lastName": "Allen",
    "state": "nh",
    "ideology": "Moderate",
    "birthYear": 1738,
    "age": 34,
    "skills": {
      "admin": 0,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 0,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Celebrity"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Horatio",
    "lastName": "Gates",
    "state": "va",
    "ideology": "Moderate",
    "birthYear": 1727,
    "age": 45,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 0,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Daniel",
    "lastName": "Boone",
    "state": "nc",
    "ideology": "Traditionalist",
    "birthYear": 1734,
    "age": 38,
    "skills": {
      "admin": 0,
      "legislative": 0,
      "judicial": 0,
      "military": 2,
      "governing": 0,
      "backroom": 0
    },
    "command": 0,
    "traits": [
      "Celebrity"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Elbridge",
    "lastName": "Gerry",
    "state": "ma",
    "ideology": "Moderate",
    "birthYear": 1744,
    "age": 28,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 3
    },
    "command": 0,
    "traits": [
      "Manipulative"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "George",
    "lastName": "Washington",
    "state": "va",
    "ideology": "Moderate",
    "birthYear": 1732,
    "age": 40,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 0,
      "military": 4,
      "governing": 2,
      "backroom": 2
    },
    "command": 1,
    "traits": [
      "Leadership"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "John",
    "lastName": "Adams",
    "state": "ma",
    "ideology": "Moderate",
    "birthYear": 1735,
    "age": 37,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 1,
    "traits": [
      "Egghead",
      "Debater"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Benjamin",
    "lastName": "Franklin",
    "state": "pa",
    "ideology": "Moderate",
    "birthYear": 1706,
    "age": 66,
    "skills": {
      "admin": 4,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 4
    },
    "command": 1,
    "traits": [
      "Celebrity",
      "Egghead"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "John",
    "lastName": "Jay",
    "state": "ny",
    "ideology": "Moderate",
    "birthYear": 1745,
    "age": 27,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Henry",
    "lastName": "Laurens",
    "state": "sc",
    "ideology": "Traditionalist",
    "birthYear": 1724,
    "age": 48,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 1,
      "military": 1,
      "governing": 2,
      "backroom": 3
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Samuel",
    "lastName": "Huntington",
    "state": "ct",
    "ideology": "Conservative",
    "birthYear": 1731,
    "age": 41,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 3,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Efficient"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Roger",
    "lastName": "Sherman",
    "state": "ct",
    "ideology": "Moderate",
    "birthYear": 1721,
    "age": 51,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "James",
    "lastName": "Wilson",
    "state": "pa",
    "ideology": "Moderate",
    "birthYear": 1742,
    "age": 30,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 4,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Egghead"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Caesar",
    "lastName": "Rodney",
    "state": "de",
    "ideology": "Moderate",
    "birthYear": 1728,
    "age": 44,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 1,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Israel",
    "lastName": "Putnam",
    "state": "ct",
    "ideology": "Moderate",
    "birthYear": 1718,
    "age": 54,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 0,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Nathanael",
    "lastName": "Greene",
    "state": "ri",
    "ideology": "Progressive",
    "birthYear": 1742,
    "age": 30,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 0,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Benedict",
    "lastName": "Arnold",
    "state": "ct",
    "ideology": "Moderate",
    "birthYear": 1741,
    "age": 31,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 0,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Military",
      "Traitor"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Daniel",
    "lastName": "Morgan",
    "state": "va",
    "ideology": "Conservative",
    "birthYear": 1736,
    "age": 36,
    "skills": {
      "admin": 0,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 0,
      "backroom": 0
    },
    "command": 0,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "George",
    "lastName": "Wythe",
    "state": "va",
    "ideology": "Liberal",
    "birthYear": 1726,
    "age": 46,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 4,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Egghead"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Robert Treat",
    "lastName": "Paine",
    "state": "ma",
    "ideology": "Progressive",
    "birthYear": 1731,
    "age": 41,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 3,
      "military": 0,
      "governing": 1,
      "backroom": 1
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Benjamin",
    "lastName": "Rush",
    "state": "pa",
    "ideology": "Progressive",
    "birthYear": 1746,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Egghead",
      "Reformist"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Thomas",
    "lastName": "McKean",
    "state": "de",
    "ideology": "Progressive",
    "birthYear": 1734,
    "age": 38,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Oliver",
    "lastName": "Ellsworth",
    "state": "ct",
    "ideology": "Progressive",
    "birthYear": 1745,
    "age": 27,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 3,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Benjamin",
    "lastName": "Lincoln",
    "state": "ma",
    "ideology": "Conservative",
    "birthYear": 1733,
    "age": 39,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 0,
      "military": 3,
      "governing": 2,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "John Paul",
    "lastName": "Jones",
    "state": "va",
    "ideology": "Moderate",
    "birthYear": 1747,
    "age": 25,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 0,
      "backroom": 0
    },
    "command": 0,
    "traits": [
      "Naval"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "John",
    "lastName": "Barry",
    "state": "pa",
    "ideology": "Moderate",
    "birthYear": 1745,
    "age": 27,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 2,
      "governing": 0,
      "backroom": 0
    },
    "command": 0,
    "traits": [
      "Naval"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Esek",
    "lastName": "Hopkins",
    "state": "ri",
    "ideology": "Moderate",
    "birthYear": 1718,
    "age": 54,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 0,
      "backroom": 0
    },
    "command": 0,
    "traits": [
      "Naval"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "William",
    "lastName": "Moultrie",
    "state": "sc",
    "ideology": "Conservative",
    "birthYear": 1730,
    "age": 42,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 1,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Arthur",
    "lastName": "St. Clair",
    "state": "pa",
    "ideology": "Conservative",
    "birthYear": 1737,
    "age": 35,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 2,
      "governing": 1,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Philip",
    "lastName": "Schuyler",
    "state": "ny",
    "ideology": "Conservative",
    "birthYear": 1733,
    "age": 39,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 0,
      "military": 2,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Timothy",
    "lastName": "Pickering",
    "state": "ma",
    "ideology": "Conservative",
    "birthYear": 1745,
    "age": 27,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 1,
      "military": 1,
      "governing": 1,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Puritan"
    ]
  },
  {
    "draftYear": 1776,
    "firstName": "James",
    "lastName": "Madison",
    "state": "va",
    "ideology": "Liberal",
    "birthYear": 1751,
    "age": 25,
    "skills": {
      "admin": 3,
      "legislative": 4,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 1,
    "traits": [
      "Egghead",
      "Reformist"
    ]
  },
  {
    "draftYear": 1780,
    "firstName": "Alexander",
    "lastName": "Hamilton",
    "state": "ny",
    "ideology": "Conservative",
    "birthYear": 1755,
    "age": 25,
    "skills": {
      "admin": 4,
      "legislative": 3,
      "judicial": 2,
      "military": 2,
      "governing": 1,
      "backroom": 3
    },
    "command": 1,
    "traits": [
      "Egghead"
    ]
  },
  {
    "draftYear": 1780,
    "firstName": "Aaron",
    "lastName": "Burr",
    "state": "ny",
    "ideology": "Moderate",
    "birthYear": 1756,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 2,
      "military": 1,
      "governing": 1,
      "backroom": 4
    },
    "command": 0,
    "traits": [
      "Manipulative"
    ]
  },
  {
    "draftYear": 1780,
    "firstName": "Rufus",
    "lastName": "King",
    "state": "ny",
    "ideology": "Conservative",
    "birthYear": 1755,
    "age": 25,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Debater"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Robert",
    "lastName": "Morris",
    "state": "pa",
    "ideology": "Conservative",
    "birthYear": 1734,
    "age": 38,
    "skills": {
      "admin": 4,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 0,
    "traits": [
      "Economics"
    ]
  },
  {
    "draftYear": 1776,
    "firstName": "Gouverneur",
    "lastName": "Morris",
    "state": "ny",
    "ideology": "Conservative",
    "birthYear": 1752,
    "age": 24,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 3,
      "military": 0,
      "governing": 1,
      "backroom": 3
    },
    "command": 0,
    "traits": [
      "Egghead",
      "Orator"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Charles Cotesworth",
    "lastName": "Pinckney",
    "state": "sc",
    "ideology": "Conservative",
    "birthYear": 1746,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 2,
      "military": 2,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Thomas",
    "lastName": "Mifflin",
    "state": "pa",
    "ideology": "Moderate",
    "birthYear": 1744,
    "age": 28,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 0,
      "military": 2,
      "governing": 3,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1784,
    "firstName": "Fisher",
    "lastName": "Ames",
    "state": "ma",
    "ideology": "Conservative",
    "birthYear": 1758,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 4,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Orator"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Theodore",
    "lastName": "Sedgwick",
    "state": "ma",
    "ideology": "Conservative",
    "birthYear": 1746,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Jonathan",
    "lastName": "Trumbull",
    "state": "ct",
    "ideology": "Conservative",
    "birthYear": 1740,
    "age": 32,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1776,
    "firstName": "Frederick",
    "lastName": "Muhlenberg",
    "state": "pa",
    "ideology": "Moderate",
    "birthYear": 1750,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1780,
    "firstName": "Abraham",
    "lastName": "Baldwin",
    "state": "ga",
    "ideology": "Liberal",
    "birthYear": 1754,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Education"
    ]
  },
  {
    "draftYear": 1784,
    "firstName": "James",
    "lastName": "Jackson",
    "state": "ga",
    "ideology": "LW Populist",
    "birthYear": 1757,
    "age": 27,
    "skills": {
      "admin": 1,
      "legislative": 3,
      "judicial": 1,
      "military": 2,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Orator"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "William",
    "lastName": "Maclay",
    "state": "pa",
    "ideology": "Progressive",
    "birthYear": 1737,
    "age": 35,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Reformist"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Robert",
    "lastName": "Livingston",
    "state": "ny",
    "ideology": "Liberal",
    "birthYear": 1746,
    "age": 26,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1780,
    "firstName": "Edmund",
    "lastName": "Randolph",
    "state": "va",
    "ideology": "Moderate",
    "birthYear": 1753,
    "age": 27,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1776,
    "firstName": "Henry",
    "lastName": "Knox",
    "state": "ma",
    "ideology": "Moderate",
    "birthYear": 1750,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 0,
      "military": 4,
      "governing": 1,
      "backroom": 1
    },
    "command": 0,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Pierce",
    "lastName": "Butler",
    "state": "sc",
    "ideology": "Traditionalist",
    "birthYear": 1744,
    "age": 28,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 1,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Ralph",
    "lastName": "Izard",
    "state": "sc",
    "ideology": "Conservative",
    "birthYear": 1742,
    "age": 30,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "William",
    "lastName": "Few",
    "state": "ga",
    "ideology": "Moderate",
    "birthYear": 1748,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Richard",
    "lastName": "Bassett",
    "state": "de",
    "ideology": "Moderate",
    "birthYear": 1745,
    "age": 27,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 1
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "George",
    "lastName": "Read",
    "state": "de",
    "ideology": "Conservative",
    "birthYear": 1733,
    "age": 39,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 1
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "John",
    "lastName": "Langdon",
    "state": "nh",
    "ideology": "Moderate",
    "birthYear": 1741,
    "age": 31,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 0,
      "military": 0,
      "governing": 3,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Paine",
    "lastName": "Wingate",
    "state": "nh",
    "ideology": "Conservative",
    "birthYear": 1739,
    "age": 33,
    "skills": {
      "admin": 1,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 1
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Caleb",
    "lastName": "Strong",
    "state": "ma",
    "ideology": "Conservative",
    "birthYear": 1745,
    "age": 27,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 1
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Tristram",
    "lastName": "Dalton",
    "state": "ma",
    "ideology": "Moderate",
    "birthYear": 1738,
    "age": 34,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 1
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "William Samuel",
    "lastName": "Johnson",
    "state": "ct",
    "ideology": "Conservative",
    "birthYear": 1727,
    "age": 45,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 3,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Egghead"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Charles",
    "lastName": "Carroll",
    "state": "md",
    "ideology": "Conservative",
    "birthYear": 1737,
    "age": 35,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 0,
    "traits": [
      "Economics"
    ]
  },
  {
    "draftYear": 1776,
    "firstName": "John",
    "lastName": "Henry",
    "state": "md",
    "ideology": "Moderate",
    "birthYear": 1750,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "William",
    "lastName": "Grayson",
    "state": "va",
    "ideology": "Progressive",
    "birthYear": 1740,
    "age": 32,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 1,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": [
      "Debater"
    ]
  },
  {
    "draftYear": 1772,
    "firstName": "Samuel",
    "lastName": "Johnston",
    "state": "nc",
    "ideology": "Conservative",
    "birthYear": 1733,
    "age": 39,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1780,
    "firstName": "Benjamin",
    "lastName": "Hawkins",
    "state": "nc",
    "ideology": "Moderate",
    "birthYear": 1754,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "Joseph",
    "lastName": "Stanton",
    "state": "ri",
    "ideology": "Progressive",
    "birthYear": 1739,
    "age": 33,
    "skills": {
      "admin": 1,
      "legislative": 2,
      "judicial": 0,
      "military": 1,
      "governing": 1,
      "backroom": 2
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1776,
    "firstName": "Theodore",
    "lastName": "Foster",
    "state": "ri",
    "ideology": "Moderate",
    "birthYear": 1752,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 1
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1772,
    "firstName": "John",
    "lastName": "Walker",
    "state": "va",
    "ideology": "Moderate",
    "birthYear": 1744,
    "age": 28,
    "skills": {
      "admin": 1,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 1
    },
    "command": 0,
    "traits": []
  },
  {
    "draftYear": 1784,
    "firstName": "John",
    "lastName": "Beckley",
    "state": "va",
    "ideology": "Moderate",
    "birthYear": 1757,
    "age": 27,
    "skills": {
      "admin": 1,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 3
    },
    "command": 0,
    "traits": [
      "Manipulative"
    ]
  },
  {
    "draftYear": 1816,
    "firstName": "James",
    "lastName": "Buchanan",
    "state": "pa",
    "ideology": "Conservative",
    "birthYear": 1791,
    "age": 25,
    "skills": {
      "admin": 4,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 3,
      "backroom": 3
    },
    "command": 4,
    "traits": [
      "Efficient"
    ]
  },
  {
    "draftYear": 1848,
    "firstName": "John C.",
    "lastName": "Breckinridge",
    "state": "ky",
    "ideology": "Conservative",
    "birthYear": 1821,
    "age": 27,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 1,
      "military": 1,
      "governing": 2,
      "backroom": 3
    },
    "command": 3,
    "traits": [
      "Orator"
    ]
  },
  {
    "draftYear": 1832,
    "firstName": "Jefferson",
    "lastName": "Davis",
    "state": "ms",
    "ideology": "Traditionalist",
    "birthYear": 1808,
    "age": 24,
    "skills": {
      "admin": 4,
      "legislative": 3,
      "judicial": 1,
      "military": 4,
      "governing": 2,
      "backroom": 3
    },
    "command": 4,
    "traits": [
      "Nationalist",
      "Military"
    ]
  },
  {
    "draftYear": 1824,
    "firstName": "James M.",
    "lastName": "Mason",
    "state": "va",
    "ideology": "Traditionalist",
    "birthYear": 1798,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 2,
    "traits": [
      "Nationalist"
    ]
  },
  {
    "draftYear": 1836,
    "firstName": "Robert",
    "lastName": "Toombs",
    "state": "ga",
    "ideology": "Traditionalist",
    "birthYear": 1810,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 4,
      "judicial": 1,
      "military": 1,
      "governing": 2,
      "backroom": 3
    },
    "command": 3,
    "traits": [
      "Orator",
      "Debater"
    ]
  },
  {
    "draftYear": 1840,
    "firstName": "Howell",
    "lastName": "Cobb",
    "state": "ga",
    "ideology": "Conservative",
    "birthYear": 1815,
    "age": 25,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 3,
      "backroom": 3
    },
    "command": 3,
    "traits": [
      "Economics"
    ]
  },
  {
    "draftYear": 1832,
    "firstName": "John B.",
    "lastName": "Floyd",
    "state": "va",
    "ideology": "Conservative",
    "birthYear": 1806,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 0,
      "military": 2,
      "governing": 3,
      "backroom": 1
    },
    "command": 2,
    "traits": [
      "Corrupt"
    ]
  },
  {
    "draftYear": 1848,
    "firstName": "James L.",
    "lastName": "Orr",
    "state": "sc",
    "ideology": "Conservative",
    "birthYear": 1822,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 2,
    "traits": []
  },
  {
    "draftYear": 1840,
    "firstName": "Stephen A.",
    "lastName": "Douglas",
    "state": "il",
    "ideology": "Moderate",
    "birthYear": 1813,
    "age": 27,
    "skills": {
      "admin": 3,
      "legislative": 4,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 4
    },
    "command": 4,
    "traits": [
      "Orator",
      "Debater"
    ]
  },
  {
    "draftYear": 1808,
    "firstName": "Lewis",
    "lastName": "Cass",
    "state": "mi",
    "ideology": "Moderate",
    "birthYear": 1782,
    "age": 26,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 2,
      "military": 1,
      "governing": 3,
      "backroom": 2
    },
    "command": 3,
    "traits": [
      "Globalist"
    ]
  },
  {
    "draftYear": 1812,
    "firstName": "William L.",
    "lastName": "Marcy",
    "state": "ny",
    "ideology": "Moderate",
    "birthYear": 1786,
    "age": 26,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 1,
      "military": 1,
      "governing": 3,
      "backroom": 3
    },
    "command": 2,
    "traits": []
  },
  {
    "draftYear": 1828,
    "firstName": "Franklin",
    "lastName": "Pierce",
    "state": "nh",
    "ideology": "Moderate",
    "birthYear": 1804,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 1,
      "governing": 2,
      "backroom": 2
    },
    "command": 2,
    "traits": [
      "Passive"
    ]
  },
  {
    "draftYear": 1824,
    "firstName": "Daniel S.",
    "lastName": "Dickinson",
    "state": "ny",
    "ideology": "Moderate",
    "birthYear": 1800,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 2,
    "traits": []
  },
  {
    "draftYear": 1832,
    "firstName": "Andrew",
    "lastName": "Johnson",
    "state": "tn",
    "ideology": "Conservative",
    "birthYear": 1808,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 2,
    "traits": [
      "Unlikable"
    ]
  },
  {
    "draftYear": 1820,
    "firstName": "John",
    "lastName": "Bell",
    "state": "tn",
    "ideology": "Moderate",
    "birthYear": 1796,
    "age": 24,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 3,
    "traits": [
      "Crisis Manager"
    ]
  },
  {
    "draftYear": 1820,
    "firstName": "Edward",
    "lastName": "Everett",
    "state": "ma",
    "ideology": "Moderate",
    "birthYear": 1794,
    "age": 26,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 2,
    "traits": [
      "Orator",
      "Education"
    ]
  },
  {
    "draftYear": 1820,
    "firstName": "Sam",
    "lastName": "Houston",
    "state": "tx",
    "ideology": "Moderate",
    "birthYear": 1793,
    "age": 27,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 4,
      "governing": 3,
      "backroom": 2
    },
    "command": 4,
    "traits": [
      "Celebrity",
      "Military"
    ]
  },
  {
    "draftYear": 1820,
    "firstName": "James K.",
    "lastName": "Polk",
    "state": "tn",
    "ideology": "Liberal",
    "birthYear": 1795,
    "age": 25,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 1,
      "military": 1,
      "governing": 2,
      "backroom": 3
    },
    "command": 3,
    "traits": [
      "Efficient"
    ]
  },
  {
    "draftYear": 1808,
    "firstName": "Thomas H.",
    "lastName": "Benton",
    "state": "mo",
    "ideology": "Liberal",
    "birthYear": 1782,
    "age": 26,
    "skills": {
      "admin": 3,
      "legislative": 4,
      "judicial": 1,
      "military": 1,
      "governing": 2,
      "backroom": 3
    },
    "command": 4,
    "traits": [
      "Orator",
      "Reformist"
    ]
  },
  {
    "draftYear": 1840,
    "firstName": "David",
    "lastName": "Wilmot",
    "state": "pa",
    "ideology": "Progressive",
    "birthYear": 1814,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 2,
    "traits": [
      "Reformist"
    ]
  },
  {
    "draftYear": 1808,
    "firstName": "Martin",
    "lastName": "Van Buren",
    "state": "ny",
    "ideology": "Liberal",
    "birthYear": 1782,
    "age": 26,
    "skills": {
      "admin": 4,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 3,
      "backroom": 5
    },
    "command": 4,
    "traits": [
      "Manipulative",
      "Magician"
    ]
  },
  {
    "draftYear": 1824,
    "firstName": "John A.",
    "lastName": "Dix",
    "state": "ny",
    "ideology": "Liberal",
    "birthYear": 1798,
    "age": 26,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 1,
      "military": 2,
      "governing": 3,
      "backroom": 2
    },
    "command": 2,
    "traits": []
  },
  {
    "draftYear": 1812,
    "firstName": "John J.",
    "lastName": "Crittenden",
    "state": "ky",
    "ideology": "Conservative",
    "birthYear": 1787,
    "age": 25,
    "skills": {
      "admin": 3,
      "legislative": 4,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 3,
    "traits": [
      "Crisis Manager"
    ]
  },
  {
    "draftYear": 1820,
    "firstName": "Edward",
    "lastName": "Bates",
    "state": "mo",
    "ideology": "Conservative",
    "birthYear": 1793,
    "age": 27,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 4,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 2,
    "traits": [
      "Integrity"
    ]
  },
  {
    "draftYear": 1832,
    "firstName": "Orville H.",
    "lastName": "Browning",
    "state": "il",
    "ideology": "Moderate",
    "birthYear": 1806,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 2,
    "traits": []
  },
  {
    "draftYear": 1836,
    "firstName": "Abraham",
    "lastName": "Lincoln",
    "state": "il",
    "ideology": "Moderate",
    "birthYear": 1809,
    "age": 27,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 2,
    "traits": [
      "Orator",
      "Integrity"
    ]
  },
  {
    "draftYear": 1832,
    "firstName": "William P.",
    "lastName": "Fessenden",
    "state": "me",
    "ideology": "Moderate",
    "birthYear": 1806,
    "age": 26,
    "skills": {
      "admin": 3,
      "legislative": 4,
      "judicial": 2,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 3,
    "traits": [
      "Economics"
    ]
  },
  {
    "draftYear": 1840,
    "firstName": "Lyman",
    "lastName": "Trumbull",
    "state": "il",
    "ideology": "Moderate",
    "birthYear": 1813,
    "age": 27,
    "skills": {
      "admin": 3,
      "legislative": 4,
      "judicial": 3,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 3,
    "traits": [
      "Integrity"
    ]
  },
  {
    "draftYear": 1836,
    "firstName": "Hannibal",
    "lastName": "Hamlin",
    "state": "me",
    "ideology": "Moderate",
    "birthYear": 1809,
    "age": 27,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 3,
      "backroom": 2
    },
    "command": 2,
    "traits": []
  },
  {
    "draftYear": 1844,
    "firstName": "John A.",
    "lastName": "Andrew",
    "state": "ma",
    "ideology": "Liberal",
    "birthYear": 1818,
    "age": 26,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 4,
      "backroom": 2
    },
    "command": 3,
    "traits": [
      "Reformist",
      "Integrity"
    ]
  },
  {
    "draftYear": 1828,
    "firstName": "William H.",
    "lastName": "Seward",
    "state": "ny",
    "ideology": "Liberal",
    "birthYear": 1801,
    "age": 27,
    "skills": {
      "admin": 3,
      "legislative": 4,
      "judicial": 2,
      "military": 0,
      "governing": 3,
      "backroom": 4
    },
    "command": 5,
    "traits": [
      "Manipulative",
      "Magician"
    ]
  },
  {
    "draftYear": 1832,
    "firstName": "Salmon P.",
    "lastName": "Chase",
    "state": "oh",
    "ideology": "Progressive",
    "birthYear": 1808,
    "age": 24,
    "skills": {
      "admin": 3,
      "legislative": 3,
      "judicial": 3,
      "military": 0,
      "governing": 4,
      "backroom": 2
    },
    "command": 3,
    "traits": [
      "Integrity",
      "Reformist"
    ]
  },
  {
    "draftYear": 1840,
    "firstName": "John C.",
    "lastName": "Frémont",
    "state": "ca",
    "ideology": "Liberal",
    "birthYear": 1813,
    "age": 27,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 0,
      "military": 3,
      "governing": 1,
      "backroom": 1
    },
    "command": 3,
    "traits": [
      "Celebrity"
    ]
  },
  {
    "draftYear": 1836,
    "firstName": "Henry",
    "lastName": "Wilson",
    "state": "ma",
    "ideology": "Progressive",
    "birthYear": 1812,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 3
    },
    "command": 2,
    "traits": [
      "Reformist"
    ]
  },
  {
    "draftYear": 1848,
    "firstName": "Schuyler",
    "lastName": "Colfax",
    "state": "in",
    "ideology": "Liberal",
    "birthYear": 1823,
    "age": 25,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 3
    },
    "command": 2,
    "traits": [
      "Charismatic"
    ]
  },
  {
    "draftYear": 1836,
    "firstName": "Charles",
    "lastName": "Sumner",
    "state": "ma",
    "ideology": "LW Populist",
    "birthYear": 1811,
    "age": 25,
    "skills": {
      "admin": 2,
      "legislative": 4,
      "judicial": 3,
      "military": 0,
      "governing": 2,
      "backroom": 1
    },
    "command": 4,
    "traits": [
      "Orator",
      "Reformist",
      "Puritan"
    ]
  },
  {
    "draftYear": 1816,
    "firstName": "Thaddeus",
    "lastName": "Stevens",
    "state": "pa",
    "ideology": "LW Populist",
    "birthYear": 1792,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 5,
      "judicial": 3,
      "military": 0,
      "governing": 1,
      "backroom": 4
    },
    "command": 4,
    "traits": [
      "Orator",
      "Reformist",
      "Manipulative"
    ]
  },
  {
    "draftYear": 1824,
    "firstName": "Benjamin",
    "lastName": "Wade",
    "state": "oh",
    "ideology": "LW Populist",
    "birthYear": 1800,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 4,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 3,
    "traits": [
      "Reformist"
    ]
  },
  {
    "draftYear": 1820,
    "firstName": "Joshua",
    "lastName": "Giddings",
    "state": "oh",
    "ideology": "LW Populist",
    "birthYear": 1795,
    "age": 25,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 2,
      "military": 0,
      "governing": 1,
      "backroom": 1
    },
    "command": 2,
    "traits": [
      "Reformist"
    ]
  },
  {
    "draftYear": 1836,
    "firstName": "Owen",
    "lastName": "Lovejoy",
    "state": "il",
    "ideology": "LW Populist",
    "birthYear": 1811,
    "age": 25,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 1
    },
    "command": 2,
    "traits": [
      "Reformist"
    ]
  },
  {
    "draftYear": 1824,
    "firstName": "Millard",
    "lastName": "Fillmore",
    "state": "ny",
    "ideology": "Conservative",
    "birthYear": 1800,
    "age": 24,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 2,
      "backroom": 2
    },
    "command": 2,
    "traits": [
      "Passive"
    ]
  },
  {
    "draftYear": 1840,
    "firstName": "Nathaniel P.",
    "lastName": "Banks",
    "state": "ma",
    "ideology": "Moderate",
    "birthYear": 1816,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 3,
      "judicial": 1,
      "military": 1,
      "governing": 2,
      "backroom": 3
    },
    "command": 3,
    "traits": [
      "Charismatic"
    ]
  },
  {
    "draftYear": 1844,
    "firstName": "Anson",
    "lastName": "Burlingame",
    "state": "ma",
    "ideology": "Moderate",
    "birthYear": 1820,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 2,
      "judicial": 1,
      "military": 0,
      "governing": 1,
      "backroom": 2
    },
    "command": 2,
    "traits": [
      "Globalist"
    ]
  },
  {
    "draftYear": 1812,
    "firstName": "Winfield",
    "lastName": "Scott",
    "state": "va",
    "ideology": "Moderate",
    "birthYear": 1786,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 0,
      "judicial": 0,
      "military": 5,
      "governing": 0,
      "backroom": 1
    },
    "command": 3,
    "traits": [
      "Military",
      "Celebrity"
    ]
  },
  {
    "draftYear": 1832,
    "firstName": "Robert E.",
    "lastName": "Lee",
    "state": "va",
    "ideology": "Conservative",
    "birthYear": 1807,
    "age": 25,
    "skills": {
      "admin": 2,
      "legislative": 0,
      "judicial": 0,
      "military": 5,
      "governing": 1,
      "backroom": 1
    },
    "command": 3,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1848,
    "firstName": "Ulysses S.",
    "lastName": "Grant",
    "state": "oh",
    "ideology": "Moderate",
    "birthYear": 1822,
    "age": 26,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 4,
      "governing": 0,
      "backroom": 0
    },
    "command": 1,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1844,
    "firstName": "William T.",
    "lastName": "Sherman",
    "state": "oh",
    "ideology": "Moderate",
    "birthYear": 1820,
    "age": 24,
    "skills": {
      "admin": 1,
      "legislative": 0,
      "judicial": 0,
      "military": 4,
      "governing": 0,
      "backroom": 0
    },
    "command": 1,
    "traits": [
      "Military"
    ]
  },
  {
    "draftYear": 1852,
    "firstName": "George B.",
    "lastName": "McClellan",
    "state": "pa",
    "ideology": "Conservative",
    "birthYear": 1826,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 0,
      "judicial": 0,
      "military": 3,
      "governing": 0,
      "backroom": 0
    },
    "command": 2,
    "traits": [
      "Military",
      "Passive"
    ]
  },
  {
    "draftYear": 1804,
    "firstName": "Roger B.",
    "lastName": "Taney",
    "state": "md",
    "ideology": "Traditionalist",
    "birthYear": 1777,
    "age": 27,
    "skills": {
      "admin": 3,
      "legislative": 2,
      "judicial": 5,
      "military": 0,
      "governing": 0,
      "backroom": 2
    },
    "command": 3,
    "traits": []
  },
  {
    "draftYear": 1812,
    "firstName": "John",
    "lastName": "Catron",
    "state": "tn",
    "ideology": "Conservative",
    "birthYear": 1786,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 4,
      "military": 0,
      "governing": 0,
      "backroom": 1
    },
    "command": 1,
    "traits": []
  },
  {
    "draftYear": 1808,
    "firstName": "Peter V.",
    "lastName": "Daniel",
    "state": "va",
    "ideology": "Traditionalist",
    "birthYear": 1784,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 4,
      "military": 0,
      "governing": 0,
      "backroom": 1
    },
    "command": 1,
    "traits": []
  },
  {
    "draftYear": 1816,
    "firstName": "Samuel",
    "lastName": "Nelson",
    "state": "ny",
    "ideology": "Conservative",
    "birthYear": 1792,
    "age": 24,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 4,
      "military": 0,
      "governing": 0,
      "backroom": 1
    },
    "command": 1,
    "traits": []
  },
  {
    "draftYear": 1820,
    "firstName": "Robert C.",
    "lastName": "Grier",
    "state": "pa",
    "ideology": "Conservative",
    "birthYear": 1794,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 4,
      "military": 0,
      "governing": 0,
      "backroom": 1
    },
    "command": 1,
    "traits": []
  },
  {
    "draftYear": 1836,
    "firstName": "Benjamin R.",
    "lastName": "Curtis",
    "state": "ma",
    "ideology": "Liberal",
    "birthYear": 1809,
    "age": 27,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 4,
      "military": 0,
      "governing": 0,
      "backroom": 1
    },
    "command": 2,
    "traits": [
      "Integrity"
    ]
  },
  {
    "draftYear": 1836,
    "firstName": "John A.",
    "lastName": "Campbell",
    "state": "al",
    "ideology": "Traditionalist",
    "birthYear": 1811,
    "age": 25,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 4,
      "military": 0,
      "governing": 0,
      "backroom": 1
    },
    "command": 1,
    "traits": []
  },
  {
    "draftYear": 1816,
    "firstName": "James M.",
    "lastName": "Wayne",
    "state": "ga",
    "ideology": "Conservative",
    "birthYear": 1790,
    "age": 26,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 4,
      "military": 0,
      "governing": 0,
      "backroom": 1
    },
    "command": 1,
    "traits": []
  },
  {
    "draftYear": 1812,
    "firstName": "John",
    "lastName": "McLean",
    "state": "oh",
    "ideology": "Liberal",
    "birthYear": 1785,
    "age": 27,
    "skills": {
      "admin": 2,
      "legislative": 1,
      "judicial": 4,
      "military": 0,
      "governing": 0,
      "backroom": 1
    },
    "command": 2,
    "traits": [
      "Integrity"
    ]
  }
];
